# Generated by Django 4.1.7 on 2023-08-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='alias',
            new_name='alias_id',
        ),
    ]
