# Generated by Django 4.1.7 on 2023-08-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablausuario',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
