# Generated by Django 4.1.7 on 2023-08-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0002_rename_alias_user_alias_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='alias_id',
            new_name='alias',
        ),
    ]
