# Generated by Django 4.1.7 on 2023-08-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0002_user_tablacomentarios_alias_tablaprueba_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imgPerfil',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='img/'),
        ),
    ]
