# Generated by Django 4.1 on 2023-09-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0002_user_tablacomentarios_alias_tablaprueba_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablacomentarios',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='tablaprueba',
            name='alias',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
