# Generated by Django 4.1.7 on 2023-08-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0002_user_alter_tablacomentarios_alias_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablapreguntas',
            old_name='senia',
            new_name='pregunta',
        ),
        migrations.AlterField(
            model_name='tablapreguntas',
            name='respuesta',
            field=models.TextField(),
        ),
    ]
