# Generated by Django 4.2.5 on 2023-10-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0002_user_tablacomentarios_alias_tablaprueba_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imgPerfil',
            field=models.ImageField(blank=True, default='img/user.png', null=True, upload_to='img/'),
        ),
    ]
