# Generated by Django 4.1.7 on 2023-08-02 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0002_user_tablausuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablausuario',
            name='clave',
        ),
        migrations.RemoveField(
            model_name='user',
            name='clave',
        ),
    ]
