# Generated by Django 4.1.7 on 2023-06-05 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0002_tablacategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaSubcategoria',
            fields=[
                ('IdSubcategoria', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='IdSubcategoria')),
                ('Subcategoria', models.TextField(max_length=30)),
                ('IdCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tablas.tablacategoria')),
            ],
        ),
    ]
