# Generated by Django 4.1.7 on 2023-07-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0002_user_tablausuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablacomentarios',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='tablapalabra',
            name='subcategoria',
        ),
        migrations.RemoveField(
            model_name='tablapreguntas',
            name='idCategoria',
        ),
        migrations.RemoveField(
            model_name='tablaprueba',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='tablaprueba',
            name='idCategoria',
        ),
        migrations.RemoveField(
            model_name='tablaprueba_pregunta',
            name='idCategoria',
        ),
        migrations.RemoveField(
            model_name='tablaprueba_pregunta',
            name='idPrueba',
        ),
        migrations.RemoveField(
            model_name='tablasubcategoria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='tablausuario',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='TablaCategoria',
        ),
        migrations.DeleteModel(
            name='TablaComentarios',
        ),
        migrations.DeleteModel(
            name='TablaPalabra',
        ),
        migrations.DeleteModel(
            name='TablaPreguntas',
        ),
        migrations.DeleteModel(
            name='TablaPrueba',
        ),
        migrations.DeleteModel(
            name='TablaPrueba_Pregunta',
        ),
        migrations.DeleteModel(
            name='TablaSubcategoria',
        ),
        migrations.DeleteModel(
            name='TablaUsuario',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
