# Generated by Django 4.1.7 on 2023-06-05 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0003_tablasubcategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaPalabra',
            fields=[
                ('Palabra', models.TextField(primary_key=True, serialize=False)),
                ('IdCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tablas.tablacategoria')),
            ],
        ),
    ]
