# Generated by Django 4.1.7 on 2023-08-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0003_remove_tablausuario_clave_remove_user_clave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablausuario',
            name='correo',
        ),
        migrations.AlterField(
            model_name='tablausuario',
            name='apellido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tablausuario',
            name='nombre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tablausuario',
            name='telefono',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Teléfono'),
        ),
    ]
