# Generated by Django 4.1.7 on 2023-08-03 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0003_rename_alias_id_user_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablausuario',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='alias',
            field=models.TextField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
