# Generated by Django 4.1.7 on 2023-06-05 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0004_tablapalabra'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaPreguntas',
            fields=[
                ('tipo', models.PositiveIntegerField(verbose_name='Tipo')),
                ('respuesta', models.TextField(max_length=50)),
                ('numeroPregunta', models.AutoField(primary_key=True, serialize=False)),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tablas.tablacategoria')),
            ],
        ),
    ]
