# Generated by Django 4.1.7 on 2023-08-03 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0004_remove_tablausuario_correo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablausuario',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='alias',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Tablas.tablausuario'),
        ),
    ]
