# Generated by Django 4.1.7 on 2023-08-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0005_remove_tablausuario_user_alter_user_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablaprueba',
            name='puntaje',
            field=models.PositiveSmallIntegerField(verbose_name='Puntaje'),
        ),
        migrations.AlterField(
            model_name='tablaprueba',
            name='tipoPrueba',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
