# Generated by Django 4.1.7 on 2023-06-12 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0006_tablaprueba_pregunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablaprueba_pregunta',
            name='idCategoria',
        ),
        migrations.RemoveField(
            model_name='tablaprueba_pregunta',
            name='idPrueba',
        ),
        migrations.RemoveField(
            model_name='tablapruebas',
            name='alias',
        ),
        migrations.DeleteModel(
            name='TablaComentarios',
        ),
        migrations.DeleteModel(
            name='TablaPrueba_Pregunta',
        ),
        migrations.DeleteModel(
            name='TablaPruebas',
        ),
        migrations.DeleteModel(
            name='TablaUsuario',
        ),
    ]
