# Generated by Django 4.1.7 on 2023-06-12 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0007_remove_tablaprueba_pregunta_idcategoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablapalabra',
            name='IdCategoria',
        ),
        migrations.RemoveField(
            model_name='tablapreguntas',
            name='idCategoria',
        ),
        migrations.RemoveField(
            model_name='tablasubcategoria',
            name='IdCategoria',
        ),
        migrations.DeleteModel(
            name='TablaCategoria',
        ),
        migrations.DeleteModel(
            name='TablaPalabra',
        ),
        migrations.DeleteModel(
            name='TablaPreguntas',
        ),
        migrations.DeleteModel(
            name='TablaSubcategoria',
        ),
    ]
