# Generated by Django 4.1.7 on 2023-06-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0008_tablausuario_tablapruebas_tablaprueba_pregunta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablacomentarios',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='tablapalabra',
            name='IdCategoria',
        ),
        migrations.RemoveField(
            model_name='tablapreguntas',
            name='idCategoria',
        ),
        migrations.RemoveField(
            model_name='tablaprueba_pregunta',
            name='idCategoria',
        ),
        migrations.RemoveField(
            model_name='tablaprueba_pregunta',
            name='idPrueba',
        ),
        migrations.RemoveField(
            model_name='tablapruebas',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='tablasubcategoria',
            name='IdCategoria',
        ),
        migrations.DeleteModel(
            name='TablaCategoria',
        ),
        migrations.DeleteModel(
            name='TablaComentarios',
        ),
        migrations.DeleteModel(
            name='TablaPalabra',
        ),
        migrations.DeleteModel(
            name='TablaPreguntas',
        ),
        migrations.DeleteModel(
            name='TablaPrueba_Pregunta',
        ),
        migrations.DeleteModel(
            name='TablaPruebas',
        ),
        migrations.DeleteModel(
            name='TablaSubcategoria',
        ),
        migrations.DeleteModel(
            name='TablaUsuario',
        ),
    ]
