# Generated by Django 4.1.7 on 2023-06-13 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0010_remove_tablapruebas_alias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaPruebas',
            fields=[
                ('idPrueba', models.AutoField(primary_key=True, serialize=False)),
                ('tipoPrueba', models.PositiveSmallIntegerField(verbose_name='Tipo de prueba')),
                ('categoria', models.TextField(max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('puntaje', models.PositiveBigIntegerField(verbose_name='Puntaje')),
                ('alias', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tablas.tablausuario')),
            ],
        ),
        migrations.CreateModel(
            name='TablaPrueba_Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.PositiveBigIntegerField(verbose_name='Puntaje')),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tablas.tablapreguntas')),
                ('idPrueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tablas.tablapruebas')),
            ],
        ),
    ]
