# Generated by Django 4.1.7 on 2023-06-13 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0011_tablapruebas_tablaprueba_pregunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablapruebas',
            name='alias',
        ),
        migrations.DeleteModel(
            name='TablaPrueba_Pregunta',
        ),
        migrations.DeleteModel(
            name='TablaPruebas',
        ),
    ]
