# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: M7VuiVdfu2cZDRA7nI2oRFQ9VhWPmwZe
            client-secret: 68OrDpGXGPpQ4OUScczMqj8X9J55dTh39zda0yRELeeNUPHEf_4ArrZpB0btKQGm
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-1hbgnwradjqq8gfy.us.auth0.com/
