# Generated by Django 4.1.7 on 2023-05-29 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TablaUsuario',
            fields=[
                ('alias', models.TextField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=30)),
                ('apellido', models.TextField(max_length=30)),
                ('telefono', models.TextField(verbose_name=int)),
                ('correo', models.TextField(max_length=30)),
                ('clave', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TablaPruebas',
            fields=[
                ('idPrueba', models.AutoField(primary_key=True, serialize=False)),
                ('tipoPrueba', models.TextField(verbose_name=int)),
                ('categoria', models.TextField(max_length=30)),
                ('fecha', models.DateTimeField()),
                ('puntaje', models.TextField(verbose_name=int)),
                ('alias', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tablas.tablausuario')),
            ],
        ),
        migrations.CreateModel(
            name='TablaComentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=30)),
                ('alias', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tablas.tablausuario')),
            ],
        ),
    ]
