# Generated by Django 4.1.7 on 2023-05-30 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablapruebas',
            name='alias',
        ),
        migrations.DeleteModel(
            name='TablaComentarios',
        ),
        migrations.DeleteModel(
            name='TablaPruebas',
        ),
        migrations.DeleteModel(
            name='TablaUsuario',
        ),
    ]
